export const LABELING_EVIDENCE_ALLOWLIST = {
  tasks: [
    'annotation',
    'annotator',
    'labeling',
    'labeler',
    'tagging',
  'dataset curation',
  'red-teaming',
  'red teaming',
  'adversarial testing',
  'evaluation',
  'rater',
  'rating',
  'quality rater',
  'judge',
  'judging',
  'scoring',
  'rubric',
  'guideline adherence',
  'guideline qa',
  'prompt writing',
  'prompt engineering',
  'response writing',
  'response rating',
  'response evaluation',
  'prompt and response',
  'prompt response',
  'data cleaning for model training',
  'model critique',
  'benchmark creation',
  'preference collection',
  'pairwise comparisons',
  'preference judgments',
  'debiasing',
  'de-biasing',
  'safety review',
  'safety reviews',
  'data specialist',
  'training specialist',
],
  labelTypes: [
    'ner',
    'named entity recognition',
    'entity linking',
    'relation extraction',
    'coreference',
    'coref',
    'coreference resolution',
    'span labeling',
    'ocr',
    'transcription',
    'speech transcription',
    'segmentation',
    'polygon',
    'bounding box',
    'bbox',
    'keypoints',
    'classification',
    'multi-label classification',
    'clustering',
    'summarization',
    'q&a',
    'question answering',
    'translation',
    'sentiment',
    'code review labeling',
    'code annotation',
    'code diff labeling',
  ],
  modalities: [
    'text',
    'document',
    'documents',
    'code',
    'image',
    'images',
    'video',
    'videos',
    'audio',
    'speech',
    'lidar',
    'point cloud',
    'screen',
    'ui',
    'html',
    'css',
    'js',
    'html/css/js code',
    'screenshots',
  ],
  tools: [
    'label studio',
    'cvat',
    'labelbox',
    'superannotate',
    'diffgram',
    'v7',
    'v7 labs',
    'roboflow',
    'prodigy',
    'doccano',
    'lighttag',
    'supervisely',
    'scale ai',
    'appen',
    'remotasks',
    'toloka',
    'surge',
    'lxt',
    'outlier ai',
    'amazon sagemaker ground truth',
    'azure ml data labeling',
    'google data labeling service',
    'sage maker ground truth',
    'sagemaker ground truth',
    'azure machine learning data labeling',
    'labelbox annotate',
  ],
  llmTraining: [
    'llm',
    'llm training',
    'ai training',
    'training data',
    'fine-tuning',
    'fine tuning',
    'finetuning',
    'instruction tuning',
    'sft',
    'supervised fine-tuning',
    'dpo',
    'rlaif',
    'rlhf',
    'reward modeling',
    'reward model',
    'reinforcement learning from human feedback',
    'evaluation harness',
    'model critique',
    'benchmark creation',
  ],
};

export type EvidenceCategory = keyof typeof LABELING_EVIDENCE_ALLOWLIST;
